module Day5 exposing (..)

import Bitwise exposing (shiftLeftBy, shiftRightBy)
import Browser
import Html exposing (div, h1, h2, p, text)
import List.Extra
import Maybe.Extra
import Parser exposing ((|.), (|=), Parser)
import Set


main =
    Browser.sandbox { init = init, update = update, view = view }


type Msg
    = NoOp


type alias Model =
    { part1 : Int
    , part1Test : Int
    , part2 : Int
    , part2Test : Int
    }


init : Model
init =
    { part1Test = solvePart1 testData
    , part1 = solvePart1 data
    , part2Test = solvePart2 testData
    , part2 = solvePart2 data
    }


update : Msg -> Model -> Model
update msg model =
    case msg of
        NoOp ->
            model


view model =
    div []
        [ h1 [] [ text "Day 5" ]
        , h2 [] [ text "Part 1" ]
        , p [] [ text (String.fromInt model.part1Test) ]
        , p [] [ text (String.fromInt model.part1) ]
        , h2 [] [ text "Part 2" ]
        , p [] [ text (String.fromInt model.part2Test) ]
        , p [] [ text (String.fromInt model.part2) ]
        ]


solvePart1 data_ =
    data_
        |> List.map String.toList
        |> List.map (List.Extra.splitAt 7)
        |> List.map
            (\l ->
                ( Tuple.first l |> calculateRow, Tuple.second l |> calculateSeat )
            )
        |> List.map (\l -> (Tuple.first l * 8) + Tuple.second l)
        |> List.sort
        |> List.reverse
        |> List.head
        |> Maybe.withDefault 0


solvePart2 data_ =
    let
        allPossibleSeatIds =
            List.range 0 127
                |> List.map
                    (\row ->
                        List.range 0 7
                            |> List.map (\seat -> ( row, seat ))
                    )
                |> List.concat
                |> List.map (\( row, seat ) -> (row * 8) + seat)
                |> Set.fromList

        takenSeats =
            data_
                |> List.map String.toList
                |> List.map (List.Extra.splitAt 7)
                |> List.map
                    (\l ->
                        ( Tuple.first l |> calculateRow, Tuple.second l |> calculateSeat )
                    )
                |> List.map (\l -> (Tuple.first l * 8) + Tuple.second l)
                |> Set.fromList

        availableSeats =
            Set.diff allPossibleSeatIds takenSeats
                |> Debug.log "availableSeats"
    in
    0


calculateRow : List Char -> Int
calculateRow rowChars =
    rowChars
        |> List.foldl
            (\char sum ->
                case char of
                    'B' ->
                        shiftLeftBy 1 sum + 1

                    'F' ->
                        shiftLeftBy 1 sum

                    _ ->
                        sum
            )
            0


calculateSeat : List Char -> Int
calculateSeat seatChars =
    seatChars
        |> List.foldl
            (\char sum ->
                case char of
                    'R' ->
                        shiftLeftBy 1 sum + 1

                    'L' ->
                        shiftLeftBy 1 sum

                    _ ->
                        sum
            )
            0


testData =
    [ "BFFFBBFRRR"
    , "FFFBBBFRRR"
    , "BBFFBBFRLL"
    ]


data =
    [ "FBBFFBBLLL"
    , "FFBFFFBRLL"
    , "FFBBBBFRRL"
    , "FBFBBBBRLL"
    , "BFBBBBFLLR"
    , "FFFBBBBLRR"
    , "BFFFFFBLLL"
    , "BBFFFBFRRL"
    , "FFBFFFFLLR"
    , "BFFFBBBRRL"
    , "FBFBFFFLRL"
    , "FFFBBFBLRR"
    , "FBFBFBFLRR"
    , "FBBBBFBRRL"
    , "BFFBFFBRRR"
    , "FBBBFBBRLL"
    , "FBFFBFBRLR"
    , "BBFBFFFLRL"
    , "FFBFFFFRLR"
    , "FFBBFBFRRR"
    , "BFBBBFBLRR"
    , "FFBBFFFLRL"
    , "FBBBBFFRLR"
    , "FBBBBBBRLR"
    , "FFBFBFBLLL"
    , "BBFBFBBLLL"
    , "FFFFFBBRRL"
    , "FBFFBFBRRR"
    , "FFFBFFFRLL"
    , "BFBFBFFLLL"
    , "BFBFFBFLLL"
    , "FFFFBFFRRL"
    , "FBFFFFFRLR"
    , "FBBFFBBLLR"
    , "BFFFFFBLRL"
    , "BFBFFFBLLR"
    , "FBBBBBBLLL"
    , "BBFBFBFLLL"
    , "FFBFFBFLRR"
    , "BBFFFBBRLL"
    , "FFBFFFFLLL"
    , "FBBFFBFLLL"
    , "FFFBBBFRRR"
    , "BFBBFBFRLL"
    , "FBBFBFFRRL"
    , "FBFBBFBLRR"
    , "FFBBBBBRLR"
    , "FFBFBFFLLL"
    , "FBFFFBFRRL"
    , "BFFBBFFRLL"
    , "BFFBBFFLLR"
    , "BBFFBFFRRL"
    , "FBFBFBFLLR"
    , "BBFFBFBLRL"
    , "BFBFBFBLRR"
    , "FFBBFBBRRL"
    , "BFBBBFBRLR"
    , "FBFFFFBLLR"
    , "BFBFFBBLRR"
    , "BBFBFBFRRR"
    , "FFBFBBBRRL"
    , "BFBFBBFRLR"
    , "FBFBBBBRLR"
    , "BFFFFBBRRR"
    , "BBFFFBFLLR"
    , "FBFFFFBRRL"
    , "BBFFBFBLLL"
    , "BFFFBBBLLL"
    , "FFBFFFBLRR"
    , "BFBFBBBRRR"
    , "FBFFBFFRRR"
    , "BFFBFFBLLL"
    , "BFBBFFFLRL"
    , "BBFBFFBRLR"
    , "FBBFFFFLLL"
    , "FBFFFFBLLL"
    , "BBFFFFBRLR"
    , "BBFBFFBRRL"
    , "FBBFBFBRRR"
    , "FBFFBFFLRR"
    , "FFBBBFBLLR"
    , "FFFFFBFRRR"
    , "BFBBBBBLLR"
    , "BBFBFFFRLL"
    , "BFFBFBBLRR"
    , "BFFBBFBRLL"
    , "FBFFBFFRLR"
    , "FBFBBFFLLR"
    , "FFFFFBFRRL"
    , "FFBFFBFRLR"
    , "FBFBBBFLLL"
    , "FFBFBBFLLR"
    , "FBFFBBBRLR"
    , "FFFBFBFLLR"
    , "BFBBFBBLRL"
    , "BFFFFBFLLL"
    , "BFBFFBFLRL"
    , "BBFFBFBLLR"
    , "BFFFBFBRRL"
    , "BBFBFFBLLR"
    , "FFBBFFFRLL"
    , "FFFFFBBRLR"
    , "FFBFBFBRLL"
    , "FBBBBFBLRR"
    , "FFFBFFFRRL"
    , "FFFFBFFLRL"
    , "FFFFBFFRLR"
    , "BFFFFFFRRR"
    , "BBFFBFBRRL"
    , "BBFBFFFLRR"
    , "FFBBBFFLLR"
    , "FBFBFBBRLR"
    , "FBBFBBBLRR"
    , "BFFBBBFRLL"
    , "BFBBFBBLLL"
    , "FBFFFBBLLR"
    , "FBBBBFFRRL"
    , "BFBBFFFLLR"
    , "BFBBBFFLRL"
    , "FFBFFBBRLL"
    , "FBFBFFBRRR"
    , "FBBFBBBLRL"
    , "BFFFBFFLRL"
    , "BFFBFFBLRR"
    , "BFBFBBFLRL"
    , "FBFBBFFRLL"
    , "BFFFFBBRRL"
    , "FFBBBBBLRL"
    , "FBBFFBFRRL"
    , "BBFFBFBRLL"
    , "FBFFFFFLRL"
    , "FFFBFBFRLR"
    , "FFBBBBFLLR"
    , "FFFBBBFRLR"
    , "FFBBFFBRRR"
    , "FFFBFFBLRL"
    , "FBFBFBBLLL"
    , "BFFFFBBLRR"
    , "BBFFBBFLLR"
    , "FFFFFFBRLL"
    , "FBBBBBBLRR"
    , "FFFFBFBLLR"
    , "BBFFBBFRRL"
    , "BFBBBBBLRR"
    , "BFBBFBBLRR"
    , "BBFFFFBRRR"
    , "BFBBBFBLLR"
    , "BBFFBBBRRR"
    , "FBBFBFBRLL"
    , "FFFFFBBLRR"
    , "BBFBFBBLLR"
    , "FBFFFBFRLR"
    , "BBFFBFFLLR"
    , "BBFBFFFRLR"
    , "FFFFBFBLRL"
    , "FFBBBBBLRR"
    , "FBBBFFBLRR"
    , "FBBFBBFRLL"
    , "FBBFBFBRLR"
    , "FFBFBBBLRL"
    , "FBFFBBBLLL"
    , "FFFBBBBRRR"
    , "FFBFFBFLRL"
    , "BFFFBBFRLL"
    , "BFFFFBBLLR"
    , "BFFFFFBRRL"
    , "BFFBFBBRRL"
    , "FFBFFFBRRL"
    , "BFFBFFFLRL"
    , "BFFBBBFLLL"
    , "FFBBFFFLRR"
    , "FBBBFFBRLL"
    , "FFBBFFFRLR"
    , "BFBFBFFRLL"
    , "FFFFBBFRRR"
    , "BFBFBBFRRL"
    , "FBFBBBFLRL"
    , "FFFBFBBRLL"
    , "FFBBBFFLLL"
    , "BBFFFBBLRL"
    , "FBBBFFBRRR"
    , "BFBFBFBLLL"
    , "FFBFFBBRLR"
    , "FFBFBBBRLR"
    , "FFFFFFBRLR"
    , "BFFBBFFLRL"
    , "FFBFFBFRRR"
    , "FFBFBFFRLL"
    , "FBFBFFBLLR"
    , "FBFBFBBRRR"
    , "FFFBBFBRRR"
    , "FBBBBFBLLR"
    , "FFFFBFBRLR"
    , "FFFBBBFRLL"
    , "FBFFBFBLLL"
    , "FBFBFFFLRR"
    , "FFFBBFFLLL"
    , "BFBFFFFLLL"
    , "BBFFFBFLLL"
    , "FFFFBFBRRL"
    , "FFBBBFBRRL"
    , "BFBFFBBRLR"
    , "FFFBBFFLRL"
    , "FFFBFBBLLR"
    , "FFBBBFFRLR"
    , "FBBBBFBLRL"
    , "BFFFBBFLLL"
    , "BFFBFBFLLR"
    , "FBFFBBFLRR"
    , "BFFBBBBLLR"
    , "FBBBFFFRRR"
    , "FBFFBFBLRL"
    , "BFFFFFFRLR"
    , "FBBBBFBRRR"
    , "FFBBBBFLRL"
    , "BBFBFFBLRL"
    , "BFBFBBBLRR"
    , "FFFFFBFLLR"
    , "FBBFFBFLLR"
    , "BFFFFBBRLL"
    , "FFBFBBBLRR"
    , "FFFFBFFLLR"
    , "BBFFFFFRLR"
    , "FBBBBFFRLL"
    , "BFFFBFBLRR"
    , "FBFBBBBLLR"
    , "BFFBFFBRLL"
    , "BFBFBFFLRR"
    , "BFFFFBFLRR"
    , "FBBFFBFLRR"
    , "BFFBBFBLLR"
    , "FBBFFFBLRL"
    , "FBFBFBBRRL"
    , "FBFFBFFRRL"
    , "BFBBFBFLLR"
    , "FFFFBFFLRR"
    , "BFBFFFBLRL"
    , "BFFBBBBRRR"
    , "FFFFBBBLRR"
    , "FFFBBFBLLL"
    , "FFBBFBFLLR"
    , "BFBBFBFLLL"
    , "FBBFBFFLLR"
    , "FFFBBFFRRR"
    , "FFBBBBBRRR"
    , "FFFBFFFRLR"
    , "BFFBFBFLRR"
    , "FBFFBFBRLL"
    , "FFFFBFFLLL"
    , "FFBBBFFRLL"
    , "FBFBFFBLLL"
    , "FBFBBBFLLR"
    , "BFBBBFFRLL"
    , "BFBBBBBRRL"
    , "FFFFFFBRRL"
    , "FBBFBBFLRL"
    , "BFFBFBBRLL"
    , "FFFFFBFLRL"
    , "BFBFFFBLRR"
    , "BBFFFBFLRR"
    , "BFBFBBBLRL"
    , "FBFFFFBRLR"
    , "BFBFBBBLLL"
    , "BFFFFFFRRL"
    , "FBBFFFBRRR"
    , "FBBFBFFLRL"
    , "BBFFFFFLRL"
    , "BFFFFBBLRL"
    , "FBFBBFFRRR"
    , "FBBFFFFLRR"
    , "FFFBFFFLRR"
    , "FBFBBFFRRL"
    , "BFFBFFBRRL"
    , "BFFBFBFRRL"
    , "FFBBFBBLLR"
    , "FBFFBFFRLL"
    , "BFBFFBBLLL"
    , "FFBBFFBLLL"
    , "BBFFFBBRRL"
    , "BFFFFFFLLL"
    , "FFBBBBFRLL"
    , "BFBBBBFRRR"
    , "BFFBBBBRLR"
    , "FBFFBBFRLL"
    , "BBFBFFBLRR"
    , "FBFFBBBLRR"
    , "BBFBFFFRRL"
    , "BFBFFFFLRR"
    , "BFBFFBBRRR"
    , "FBBFFFBLLL"
    , "BFFBBBFRLR"
    , "BFFFFBFRLL"
    , "FBFBBBBRRL"
    , "BBFFBBFLRL"
    , "FBBBBFFLLR"
    , "BFBBFFBRRR"
    , "FBBFFBBLRR"
    , "FBBBBBBRRL"
    , "BBFFFBBLLR"
    , "BFBBBBFLRL"
    , "BFFBFFFRLR"
    , "FFFFBFBRRR"
    , "FFFFBFBRLL"
    , "BFFFFFFRLL"
    , "BFFFBBBRLL"
    , "FFFFFBBLLL"
    , "FBFFFBFLRR"
    , "FBFBFBFLLL"
    , "BFBBFFBRLL"
    , "BFFFBBFRLR"
    , "BFBBFFFRLL"
    , "FFFBBFBLRL"
    , "BBFFFFFLRR"
    , "BBFFFBFRLR"
    , "BFBBBBFLRR"
    , "FBFFFBBLLL"
    , "BBFFBFBRRR"
    , "FBFBFBBLRR"
    , "FBBFBFFRLR"
    , "FBFBBBBLLL"
    , "FFFBBFBLLR"
    , "FFFFBBBRRL"
    , "FFBBBBFRLR"
    , "FFFBFFBRRL"
    , "BFBBFBBLLR"
    , "FFBFFFFLRL"
    , "BFFBFBFRLR"
    , "FFBBFBBLLL"
    , "BFFBBBFLRL"
    , "FFFFFBFRLL"
    , "BFFBFFBRLR"
    , "BFFFBFFRRL"
    , "BFBFBBBRLL"
    , "BFFFFFBLRR"
    , "FBBFFBBRLL"
    , "FFFFBBBLRL"
    , "BBFFFFBLRR"
    , "BFBFBBBLLR"
    , "BFFFBFFRLR"
    , "BFBBFBFRRR"
    , "BFFBBBFLRR"
    , "FFBFBBFRRR"
    , "FBBBFBFRLR"
    , "BFBFFBBRLL"
    , "BBFFBFFRLL"
    , "BFFFBFBLLR"
    , "FBFBBFFLRL"
    , "BFFFFBBLLL"
    , "BFBBFBBRRL"
    , "BFFFBFFLLL"
    , "BFBBBFBLLL"
    , "FFBBFBFLRR"
    , "FFBBFBFRLR"
    , "BFBBBFFRRR"
    , "BBFBFFFLLL"
    , "BFFFFFBRLL"
    , "FBBFBBFRRR"
    , "BFFFBBFLRR"
    , "BFFBBBFRRL"
    , "FFBFFFFRRL"
    , "FBFFBFBLRR"
    , "FFBFBFBRLR"
    , "BBFFBFFLRR"
    , "BFFBBFFLLL"
    , "FFBBBFBRRR"
    , "BBFFBFFRRR"
    , "FBBFFFFRRR"
    , "FBBBBFFLRR"
    , "FBBFBBBRRR"
    , "FFBFBFBLRL"
    , "FBBFFFBLRR"
    , "FBFFBFFLRL"
    , "BFBBFFFRRR"
    , "FBFBBBFRLR"
    , "BFFFFFBRRR"
    , "FBFBFFFRRR"
    , "BBFFFBFLRL"
    , "FFBFBFBLLR"
    , "FBFFFBBRRL"
    , "FBBBFFBLLL"
    , "BFBFBFFRRR"
    , "FBFFBBBRLL"
    , "FFBFFBBLLR"
    , "FFBBFBBRLL"
    , "BFBFBBFRLL"
    , "BFBBFFBLLL"
    , "BFFBBBFRRR"
    , "BFBFBFBRRL"
    , "BFFFFFFLLR"
    , "BFFFBBBRRR"
    , "FBBBFBFRRR"
    , "FFFBFFBRLL"
    , "BFFFFBFLRL"
    , "FBFBBFFRLR"
    , "FBBBBBFLRL"
    , "FFFBBBFRRL"
    , "BFBFFFFLLR"
    , "FBFFFBBLRR"
    , "FBBFBBBRRL"
    , "FFFBBBFLRR"
    , "BFBFFBFRRL"
    , "BFFFBBFRRL"
    , "FBBBFFBLLR"
    , "FFBBFBBLRL"
    , "BBFBFBFRLR"
    , "FFBFFBFLLL"
    , "FFFFBFBLLL"
    , "BBFFFFBRLL"
    , "FBFFFBBRLR"
    , "FFBBBFFRRR"
    , "FFFBFFFRRR"
    , "FFBFBBBLLR"
    , "FFBFFFBRLR"
    , "FFBBBFBLRR"
    , "BFFBBBBLRL"
    , "BFFFFBFRRR"
    , "BBFBFBFRLL"
    , "FBFBBBFLRR"
    , "FFFFFBFLLL"
    , "BFBBBFFLLR"
    , "BFFBFBFRRR"
    , "BFBBFFBLRR"
    , "BBFFFBBRLR"
    , "FBBBBBBLRL"
    , "BFFBBBBRRL"
    , "FFBFBFFRLR"
    , "BFFFFFBLLR"
    , "BBFFFFBRRL"
    , "FFFBBFFLRR"
    , "BFFFFBFRRL"
    , "BBFFBFFLRL"
    , "BBFBFBFLRR"
    , "FBFBBBBLRR"
    , "BFFBBFBRRR"
    , "FFFBBBBRLL"
    , "FBFBBBFRRL"
    , "FFFFFFBRRR"
    , "BFFFFFFLRL"
    , "FFBBFFFLLR"
    , "FBBFBFBLLL"
    , "FBBFBBFRLR"
    , "BFFBFFBLLR"
    , "FBFBBFBRLL"
    , "FBFBFBFLRL"
    , "FFBFFFBLLR"
    , "FBBFFBBLRL"
    , "FFFBBBBLLR"
    , "BFFBBBBLRR"
    , "BFFBFBBLLR"
    , "FFBBFFBRLR"
    , "FBBBBFFLLL"
    , "BFFFFFBRLR"
    , "BFBBBBFRLL"
    , "FFFBBFFRLR"
    , "BFFFBFBLLL"
    , "BBFFFFFRRL"
    , "FBFFFFBRLL"
    , "BFBFBFBLRL"
    , "FBBFBBFLRR"
    , "FFBFBBFLRR"
    , "FFBFBFFLRR"
    , "FFBFFFFRLL"
    , "BFBFBFBRRR"
    , "FBBBBFFLRL"
    , "FFBFFFBLLL"
    , "BFBBBFFRLR"
    , "FBFBFFBRLL"
    , "FBBBBBFRRL"
    , "FBFFBFFLLL"
    , "BBFFBBBLLR"
    , "BFFFBFFRRR"
    , "BBFFBBBRLL"
    , "BBFFFBBLRR"
    , "FBBFBBBRLR"
    , "BFBFBBFRRR"
    , "FBFFBBFLRL"
    , "FFFFBBFLRR"
    , "BFFFBFBRLL"
    , "BBFFFFFRLL"
    , "FFFBFBFRRR"
    , "BFBBBBFLLL"
    , "FFBBBFBRLR"
    , "FFFFBBBRRR"
    , "BFBFFBFRLR"
    , "FBFFBBFLLL"
    , "FFBFFBBLRR"
    , "FBFBFFBLRR"
    , "FFBFFBBRRL"
    , "FFFBBBBRRL"
    , "BFFBFBBLRL"
    , "BBFFBBBLRR"
    , "FFFBBFBRLL"
    , "FFFBFBBLRL"
    , "BFBFFFBRRL"
    , "FBBFFFFLLR"
    , "BBFBFFBLLL"
    , "BFBFBBFLLR"
    , "BFFBFBBRRR"
    , "FBFFFFFLLR"
    , "FFBBBFFLRL"
    , "FBFFBBFRLR"
    , "BFFFBFBLRL"
    , "FBFBBBFRRR"
    , "FFBFFBFRRL"
    , "FBFBBFBRLR"
    , "BFBFBFFRLR"
    , "FBFFBBBRRR"
    , "BBFBFFFLLR"
    , "FBBFBBBLLL"
    , "FFBBBFBLLL"
    , "FFBFFFFRRR"
    , "BFFBFBFLLL"
    , "BFFBBBFLLR"
    , "FBBBBBBRLL"
    , "FBBFFBFRLL"
    , "FFFBFFBLLR"
    , "FFBBFFBLRL"
    , "BFBBFBFLRR"
    , "BFBFFFBLLL"
    , "FBFFFBBRRR"
    , "FFBFBFFLLR"
    , "FBFFBBBRRL"
    , "FBBBBFBLLL"
    , "FFFFFBBLLR"
    , "FBBFBFBLRL"
    , "BFBBFBBRLL"
    , "FFFFBFBLRR"
    , "BBFFBBFLLL"
    , "FBBBFBFRLL"
    , "FBFBBFBLLL"
    , "BBFBFBFLLR"
    , "BFBFBFBRLR"
    , "FFFFFBFRLR"
    , "FFFFFBBRLL"
    , "FBFBFBFRRR"
    , "FBBBFBFLRL"
    , "BBFFBBBLRL"
    , "FFBBBBBRLL"
    , "FBBBFBBRRR"
    , "BFFFBBBLLR"
    , "BFBBBBBRLL"
    , "FFFFFBBLRL"
    , "BBFFBFFRLR"
    , "BFBFBFBRLL"
    , "FFFFBBFLLL"
    , "BFBFBFFRRL"
    , "FFBBFFBLLR"
    , "BFBBFFFLLL"
    , "BFBBFFBRLR"
    , "FBFBFFBRLR"
    , "FBFFFBFRLL"
    , "FBBFBFFLRR"
    , "FBBFFBFRRR"
    , "BFBFFFFRLL"
    , "BFFFBBBLRL"
    , "FBFBBBBRRR"
    , "BBFFBBFLRR"
    , "FBBBBFBRLL"
    , "BBFFBBBRRL"
    , "BFBBBFFLLL"
    , "FBFFFFBLRL"
    , "FBFFFFFRRL"
    , "BFBBBFFLRR"
    , "FBBFBFBLRR"
    , "FBFBFBBLRL"
    , "FFBFBFFRRL"
    , "BFFBBFBRLR"
    , "FFBFFBBLLL"
    , "FBBBFBBLLL"
    , "FBBBFBBRRL"
    , "FBBBFBBLLR"
    , "FBFFFBFLLL"
    , "FBBBFFBRLR"
    , "FBBFBBBRLL"
    , "FBBFFFBLLR"
    , "FFFBFBBRRR"
    , "FBBFFFFLRL"
    , "BFFFFBFRLR"
    , "FBBBFFFLLL"
    , "FFBBFBFLLL"
    , "BBFFFFFRRR"
    , "BBFFFBFRRR"
    , "FFBFFBBLRL"
    , "FBBBFFBLRL"
    , "FFBBFBFRRL"
    , "FBFFFBFLRL"
    , "FBBBFFFLRL"
    , "FFFFBBBRLR"
    , "FFBBFBBRLR"
    , "FBFBFFBRRL"
    , "BFBFFBFRRR"
    , "BFBFBFFLRL"
    , "BFFBFFFLLL"
    , "FBBFBFBRRL"
    , "FFBBBFBLRL"
    , "BFFFFBFLLR"
    , "FBBBFBFLLL"
    , "FBFFFBBLRL"
    , "FBBFFFBRRL"
    , "FBBBBBFLLR"
    , "FBBBFBFRRL"
    , "FFFBBFBRRL"
    , "FBBBFFBRRL"
    , "FBFBFBBRLL"
    , "BFBBBBBLLL"
    , "FBFBFFFLLR"
    , "FFFBFFBRLR"
    , "BBFFBFBLRR"
    , "BFFFBFFLLR"
    , "FBBFBBFRRL"
    , "FFBBBBBLLL"
    , "FBBFBFFRLL"
    , "FFFBBBFLRL"
    , "FFBBBBFLRR"
    , "FBFFFFFRLL"
    , "BBFFFFBLLR"
    , "FFFFBBFRRL"
    , "FFBBBBFRRR"
    , "FBBBFBBLRL"
    , "BFFBBFBLRL"
    , "BFBBFFFRLR"
    , "FFFBFBBRRL"
    , "BBFBFBFRRL"
    , "FFFBBBFLLR"
    , "BFFFFBBRLR"
    , "BFFBFFFLLR"
    , "BBFBFFFRRR"
    , "FFFFBBFRLR"
    , "BFBBBFBRRR"
    , "FBFBBBBLRL"
    , "FFFFBBFLLR"
    , "FBFBBBFRLL"
    , "BFBBFBBRLR"
    , "FFBBFFFRRR"
    , "FFBBBFBRLL"
    , "FBBFFBFLRL"
    , "BFBFFFBRRR"
    , "BFFFBBBRLR"
    , "FFFFBFFRRR"
    , "FFBBFFBLRR"
    , "FBBFBFBLLR"
    , "FFFBBBFLLL"
    , "FBBBBBFLLL"
    , "FFFFBBBLLL"
    , "FFFBFFBLLL"
    , "BFBBBBBRLR"
    , "BFBFBBFLRR"
    , "FBFBBFBRRR"
    , "BFBBFFFLRR"
    , "FFBBFFFLLL"
    , "BFFFBBFLLR"
    , "FFBBFBFRLL"
    , "FBBBFFFRLL"
    , "FFFBBFBRLR"
    , "BFBFFBFLRR"
    , "FBFBBFBLLR"
    , "FBFFFFBRRR"
    , "FFFBFBBLLL"
    , "FBFBFFFRRL"
    , "FFFBFBFLRR"
    , "FFBBBBBRRL"
    , "FFFBFFFLLR"
    , "BFFFBFFRLL"
    , "BFBBBBBLRL"
    , "FBBBFBFLRR"
    , "FFFFBBBLLR"
    , "BFFFBFFLRR"
    , "FBBBBBFLRR"
    , "FBBBBBFRLR"
    , "BFFBFFFRRR"
    , "FFBFBBFLRL"
    , "FFBFBBFRRL"
    , "FFBFFBBRRR"
    , "FFFFBBFRLL"
    , "BBFBFBFLRL"
    , "FBFBBFFLLL"
    , "BBFFFFBLLL"
    , "FBBBBFFRRR"
    , "BFFBFBFRLL"
    , "BFBBFBFRRL"
    , "FFBFBBFLLL"
    , "FBFFFBFRRR"
    , "FFBFFBFLLR"
    , "BFBBFFBRRL"
    , "FBBFFBBRRR"
    , "FFBFBBBRLL"
    , "FBBBBBBLLR"
    , "FBFBBFBRRL"
    , "BFFBFFFRLL"
    , "BBFFBBFRRR"
    , "FBBBBBFRLL"
    , "FBBFFFFRLR"
    , "FBBFFBBRLR"
    , "BFBFBFBLLR"
    , "FBFFBFBRRL"
    , "FFFBBFFRRL"
    , "FFBFBBFRLR"
    , "BFFBFBBRLR"
    , "BFFFBFBRRR"
    , "BFBBBFFRRL"
    , "FBBBFBBLRR"
    , "FFFBFBFRLL"
    , "FFBBFFBRLL"
    , "FFFBBBBRLR"
    , "FBBBFBFLLR"
    , "BFBFBBBRRL"
    , "FBBBFFFRLR"
    , "FBFFFFFLRR"
    , "FFBFBFFRRR"
    , "FFFBFBBLRR"
    , "FBBFBFFLLL"
    , "FFBFFBFRLL"
    , "FFBBBFFLRR"
    , "FFBFBFBRRR"
    , "FFFBBBBLRL"
    , "FFBFBFFLRL"
    , "FBFBBFBLRL"
    , "FFFBFBFLRL"
    , "BFBFFBFLLR"
    , "BBFFFBFRLL"
    , "FFBBBBBLLR"
    , "BBFFFBBLLL"
    , "BBFBFFBRRR"
    , "BFBFFFBRLL"
    , "FFFBFBFRRL"
    , "FFBFFFFLRR"
    , "BBFFFFFLLL"
    , "FBBBFFFLRR"
    , "BFFFBBFRRR"
    , "FBBFBBBLLR"
    , "BFBFFFFRRL"
    , "FFBBFFBRRL"
    , "BFBFFBBLRL"
    , "BBFFFBBRRR"
    , "FFFBBFFRLL"
    , "BFFBBFBRRL"
    , "BFFFFFFLRR"
    , "BFBBBBFRLR"
    , "FBBFFBFRLR"
    , "BFFBBFFRRL"
    , "BFFBFFFRRL"
    , "FFFFBBBRLL"
    , "FBFBFFFRLR"
    , "BBFFBBFRLR"
    , "BBFFBBFRLL"
    , "BFFFBBFLRL"
    , "FBFFBFFLLR"
    , "BFBBFBFLRL"
    , "FBFBFBFRLL"
    , "BFBFBBBRLR"
    , "BFBFFBBLLR"
    , "FBBBBFBRLR"
    , "FBFFFFBLRR"
    , "FBFFBBFRRR"
    , "BBFFBFFLLL"
    , "FFFBFBFLLL"
    , "BFFBBFFRRR"
    , "FBBFBFFRRR"
    , "BBFFBBBRLR"
    , "FFFBFFBLRR"
    , "FBFBFBFRLR"
    , "BFBBBBBRRR"
    , "BFFBFBFLRL"
    , "BBFFBBBLLL"
    , "BBFFFFFLLR"
    , "BFBFFBFRLL"
    , "BFBBBBFRRL"
    , "BFBBFFBLRL"
    , "BFFBBFBLLL"
    , "BFFBBBBLLL"
    , "BFBFBBFLLL"
    , "FBFBFFFRLL"
    , "FBFBFBFRRL"
    , "BFFBFBBLLL"
    , "FFBBFBBRRR"
    , "FFFBFFBRRR"
    , "FBFFFBFLLR"
    , "FBFFFFFRRR"
    , "FBBFBBFLLL"
    , "FFFBFBBRLR"
    , "FBFFFFFLLL"
    , "FBBFFFFRRL"
    , "BFBBFFBLLR"
    , "BBFBFBBLRL"
    , "FBBFBBFLLR"
    , "BFBFFFFLRL"
    , "FFBBFBBLRR"
    , "BFBBBFBLRL"
    , "BFFBBFFRLR"
    , "FFFFBFFRLL"
    , "BFFBBFFLRR"
    , "FBBBFBBRLR"
    , "FBFBFFFLLL"
    , "FFBBBFFRRL"
    , "BFBBFBFRLR"
    , "FBFFFBBRLL"
    , "FFFBFFFLRL"
    , "BFBBBFBRRL"
    , "FBBFFFBRLR"
    , "FFBBBBFLLL"
    , "FBBBFFFLLR"
    , "FBFFBBFLLR"
    , "FFBFBBFRLL"
    , "BBFFBFBRLR"
    , "FBFFBBBLLR"
    , "FFBFBFBRRL"
    , "BFFBFFBLRL"
    , "FBFFBFBLLR"
    , "FFBFBFBLRR"
    , "FFBBFBFLRL"
    , "FFBBFFFRRL"
    , "BFBFBFFLLR"
    , "FBBBBBBRRR"
    , "BFBFFFFRLR"
    , "BFFBBBBRLL"
    , "FFFFFBBRRR"
    , "FFBFFFBRRR"
    , "FFFBFFFLLL"
    , "BFBFFFFRRR"
    , "FBBBBBFRRR"
    , "FBBBFFFRRL"
    , "FBBFFFFRLL"
    , "FFFFFBFLRR"
    , "FFBFBBBLLL"
    , "BFBFFBBRRL"
    , "FFFFBBFLRL"
    , "BFBBBFBRLL"
    , "FFBFFFBLRL"
    , "FBBFFFBRLL"
    , "BFFBBFBLRR"
    , "FFFBBFFLLR"
    , "FBBFFBBRRL"
    , "FFBFBBBRRR"
    , "FBFBFFBLRL"
    , "BFBBFBBRRR"
    , "BBFFFFBLRL"
    , "FBFBFBBLLR"
    , "BFFFBBBLRR"
    , "BFBFFFBRLR"
    , "FFFBBBBLLL"
    , "BFFBFFFLRR"
    , "BFBBFFFRRL"
    , "FBFFBBBLRL"
    , "FBFBBFFLRR"
    , "FBFFBBFRRL"
    , "BBFBFFBRLL"
    ]
